### ISSUE TITLE
"you must always use the bracket notation"

### ISSUE THREAD

**Issue by jpmckinney** [openownership/bods-dev-handbook#3]
From https://openownership.github.io/bods-dev-handbook/this_handbook.html

A little-known feature of Markdown is that you can link bare URLs with angle brackets, e.g.

    <http://example.com>

becomes:

<http://example.com>

(GitHub renders bare URLs as links even without angle brackets – try it in a Markdown file.)

**Comment by kd-ods** [comment]
Thanks for the pro-tip! Have now updated that page:

https://openownership.github.io/bods-dev-handbook/this_handbook.html
