### ISSUE TITLE
Update docs section of the handbook

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/bods-dev-handbook#32]
I think this [section](https://github.com/openownership/bods-dev-handbook/blob/master/tools.md#bods-docs-theme-and-vagrant-box
) of the dev handbook is now slightly out-of-date following https://github.com/openownership/data-standard/pull/404, and should clarify the difference between editorial changes to the docs and working on the theme.

**Comment by kd-ods** [comment]
Updated now: https://github.com/openownership/bods-dev-handbook/blob/master/tools.md
