### ISSUE TITLE
Add guidance on maintenance of the reference.rst page

### ISSUE THREAD

**Issue by kd-ods** [openownership/bods-dev-handbook#38]
Some useful guidance on how to edit and maintain the reference.rst page in the docs is needed. The page makes heavy use of custom sphinx directives and options and their use should be explained. Additionally, the page should be kept in alphabetical order and link anchors maintained.

Anything to add here @siwhitehouse?

**Comment by siwhitehouse** [comment]
There is nothing to add from me. I think you have covered the requirements here.

**Comment by kathryn-ods** [comment]
@kd-ods please can I check what maintaining link anchors entails? Like just making sure links aren't broken?

**Comment by kathryn-ods** [comment]
I'm adding in some guidance to the Style Guide as part of #53

**Comment by kd-ods** [comment]
Sorry @kathryn-ods - just realised I didn't reply. RST link anchors are those lines beginning dot dot space underscore:

```
.. _this-is-the-link-anchor-text
```

**Comment by kathryn-ods** [comment]
Thanks @kd-ods and those need to be maintained so that the sections in the reference page can be linked to?

**Comment by kd-ods** [comment]
Yes. For example, the ['Identifier object' link here](https://standard.openownership.org/en/0.3.0/schema/guidance/identifiers.html) uses one of the those anchors.

**Comment by kathryn-ods** [comment]
Thanks @kd-ods - have added some guidance in the style guide.
