### ISSUE TITLE
FYI, OCDS considering moving its handbook to Gitbook

### ISSUE THREAD

**Issue by jpmckinney** [openownership/bods-dev-handbook#4]
I think GitHub Pages makes a lot of sense.

The [OCDS handbook](https://github.com/open-contracting/standard-development-handbook) uses Sphinx, but doesn't take advantage of any of its features, really. We have some other process documentation in Google Drive, and we're considering combining both into Gitbook (free for open-source), as it retains the features we use from Google Docs and is simpler to edit and deploy than Sphinx+ReadTheDocs.

Feel free to close this issue, as just knowledge sharing.

**Comment by kd-ods** [comment]
Thanks @jpmckinney - useful intel. Keep us posted on how it goes.
