### ISSUE TITLE
FYI, OCDS using Airtable for tools

### ISSUE THREAD

**Issue by jpmckinney** [openownership/bods-dev-handbook#5]
Instead of a list like https://openownership.github.io/bods-dev-handbook/tools.html, we have an Airtable accessible from https://www.open-contracting.org/resources/open-contracting-tools-directory/

We're not entirely satisfied with the available views within Airtable, but we'll continue to use it at least for data entry, as Airtable offers an API, with which we can create other views whenever we decide to.

Feel free to close this issue, as just knowledge sharing.

**Comment by kd-ods** [comment]
Noted with thanks, @jpmckinney!
