### ISSUE TITLE
Clarify use of 'legal entity' in style guide

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/bods-dev-handbook#54]
The current draft says:

> use 'entity,' 'legal person' or specific descriptors like 'trust' to describe legal entities

This is potentially confusing as a trust is not a legal entity (i.e., it doesn't have legal personhood). To some extent this is a function of the confusion in the schema, where all non-natural persons are described as types of entity, but the human-facing documentation should address that issue. 

I think this could be solved by being explicit about the FATF-aligned distinction between legal persons and legal arrangements. So the above could become something like:

> use 'legal entity,' 'legal person' or specific descriptors like 'registered company' to describe entities with legal personality
> use 'legal arrangement' or specific descriptors like 'trust' to describe legal arrangements

**Comment by kathryn-ods** [comment]
Good spot thank you @ScatteredInk! I have made that change
