### ISSUE TITLE
Document how codelists are managed for BODS

### ISSUE THREAD

**Issue by kd-ods** [openownership/bods-dev-handbook#6]
I've added a placeholder here https://github.com/openownership/bods-dev-handbook/blob/master/compiling_schema.md#codelists.

Could one of the devs take a look and document what they can on the technical side? (Assigning to James in the first instance.) We'll need to think about the actual workflow around making a change to a codelist; i.e. do we only sync the schema to the codelists (if there have been edits) as part of a pre-release-freeze process?

**Comment by stevenday** [comment]
Just a note to say that the technical context has changed here following our decision to archive BODSKit. @Bjwebb - if it's easy to weigh in on @kd-ods' question here, in the context of the work you've done looking at these repos recently, please do so.

**Comment by kd-ods** [comment]
@rhiaro - I think this is the last thing to do to wrap up the documentation-side of the codelists work.
