### ISSUE TITLE
Write documention that describes how to run and add tests in schema repo

### ISSUE THREAD

**Issue by ScatteredInk** [openownership/bods-dev-handbook#8]
It's not clear how to do this atm.

Should cover:

- adding tests for valid statements / packages;
- adding tests for invalid statements / packages;

Running the tests.
Running flake8.

**Comment by kd-ods** [comment]
To add some detail. The documentation should explain:

- What the test setup is in the repo. (e.g. where the tests reside ... /test directory)
- What the tests do or look for.
- Whether and when the tests are run automatically.
- How they can be run locally (e.g. for development)
- Whether they can be run in isolation (eg just test_csv.py)
- How to add test data (is 'fixtures' the right term??)

(@siwhitehouse @ScatteredInk - anything to add here?)

**Comment by ScatteredInk** [comment]
Thanks @kd-ods, this looks good.

> Whether and when the tests are run automatically.

I think an overview of the CI/build process would be helpful, including the rules on merging - this feels like an assumption at the moment.

We might also benefit from a high-level statement of _what_ should be tested and what is tested, e.g. test all example data, code conventions.

**Comment by kd-ods** [comment]
[This ticket](https://github.com/openownership/data-standard/issues/119) in the main repo can be closed once the dev handbook is updated with test info.

**Comment by rhiaro** [comment]
Fixed in #58
